# 节点专属 VictoriaMetrics 配置
- configCode: c1   # 配置项编号，用于个性化配置和公共配置排重，个性化配置优先
  # nacos的dataid
  fileName:
  # nacos group
  group: k8s
  # 配置存储路径
  storePath: /home/cib/agent/config
  # 是否对storePath执行配置清理，默认false关闭
  # 配置清理只对按group批量拉取配置有效
  enableClean: true
  # 重命名配置文件，默认不重命名
  reFileName: 123
  # 配置文件权限
  fileMode: 0644
  # 配置重载脚本
  reloadScript: